name: Publish Packages
on:
  push:
    branches: [ build-package ]
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Package script
        run: /root/packaging_scripts/package.py ${{github.workspace}}

